export const userActionConstants = {
  USERS_DETAILS_DATA_INITIATE: "USERS_DETAILS_DATA_INITIATE",
  USERS_DETAILS_DATA_SUCCESS: "USERS_DETAILS_DATA_SUCCESS",
  USERS_DETAILS_DATA_FAILURE: "USERS_DETAILS_DATA_FAILURE",
};
